**Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

**Importing the dataset

In [2]:
ds1 = pd.read_excel(r'C:\Users\Pawan B Shetty\Desktop\DS projects\Breast cancer Prediction\project_dataset.xlsx')

**Preprocessing

In [3]:
ds1.age.replace(['10-19', '20-29', '30-39', '40-49','50-59', '60-69', '70-79', '80-89', '90-99'], [1, 2, 3, 4, 5, 6, 7, 8, 9], inplace=True)


In [4]:
ds1.tumorsize.unique()

array(['15-19', '35-39', '30-34', '25-29', '40-44', '10-14', '0-4',
       '20-24', '45-49', '50-54', '5-9'], dtype=object)

In [5]:
ds1.tumorsize.replace(['0-4','5-9','10-14','15-19','20-24','25-29','30-34','35-39','40-44','45-49','50-54','55-59'], [1, 2,3,4,5,6,7,8,9,10,11,12], inplace=True)

In [6]:
ds1.invnodes.unique()

array(['0-2', '3-5', '15-17', '6-8', '9-11', '24-26', '12-14'],
      dtype=object)

In [7]:
ds1.invnodes.replace(['0-2', '3-5', '15-17', '6-8', '9-11', '24-26', '12-14'],[1,2,6,3,4,7,5], inplace=True)

In [8]:
X = ds1.iloc[:, :-1].values
y = ds1.iloc[:, -1].values

In [9]:
print(X[0:5, :])

[[4 'premeno' 4 1 'yes' 3 'right' 'left_up' 'no']
 [5 'ge40' 4 1 'no' 1 'right' 'central' 'no']
 [5 'ge40' 8 1 'no' 2 'left' 'left_low' 'no']
 [4 'premeno' 8 1 'yes' 3 'right' 'left_low' 'yes']
 [4 'premeno' 7 2 'yes' 2 'left' 'right_up' 'no']]


In [10]:
print(y)

['recurrence-events' 'no-recurrence-events' 'recurrence-events'
 'no-recurrence-events' 'recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'no-recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'no-recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'no-recurrence-events' 'recurrence-events'
 'no-recurrence-events' 'no-recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'no-recurrence-events' 'recurrence-events'
 'no-recurrence-events' 'no-recurrence-events' 'no-recurrence-events'
 'recurrence-events' 'no-recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'no-recurrence-events' 'recurrence-events'
 'recurrence-events' 'no-recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'no-recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'recurrence-events' 'no-recurrence-events'
 'no-recurrence-events' 'recurrence-events' 'no-re

**label encoding

In [11]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()
le4 = LabelEncoder()
X[:, 4] = le1.fit_transform(X[:, 4])
X[:, 6] = le2.fit_transform(X[:, 6])
X[:, 8] = le3.fit_transform(X[:, 8])
y = le4.fit_transform(y)

In [12]:
print(X[0:5, :])

[[4 'premeno' 4 1 1 3 1 'left_up' 0]
 [5 'ge40' 4 1 0 1 1 'central' 0]
 [5 'ge40' 8 1 0 2 0 'left_low' 0]
 [4 'premeno' 8 1 1 3 1 'left_low' 1]
 [4 'premeno' 7 2 1 2 0 'right_up' 0]]


In [13]:
print(y)

[1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1
 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 1 1 0 0 0
 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 0 1 0 1 0
 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 0 1 0 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0
 1 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0
 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1
 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 1 0 1 0 0
 0 1 0 0 1 0 0 0 0 0 1 0 

**Categorical Encoding

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1,7])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
print(X[0:6, :])

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 4 4 1 1 3 1 0]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 5 4 1 0 1 1 0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 5 8 1 0 2 0 0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 4 8 1 1 3 1 1]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 4 7 2 1 2 0 0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 5 6 2 0 2 1 1]]


**Splitting into training and test data

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.12, random_state = 1)

In [17]:
print(y_train)

[1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0
 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0
 0 0 1 0 0 1 1 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0
 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1
 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 1 1 0 0
 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1
 0 1 1 1 1 0 0 0 1 1 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
print(X_train[0:6, :])

[[-0.91530201 -0.1491633   0.95621747 -0.27969065 -0.81485207 -0.68477479
  -0.29931851  2.62224913 -0.68242389  0.55495079 -0.47203723  1.91632888
   1.24668099  1.06887186 -0.57967737]
 [ 1.09253556 -0.1491633  -1.04578721 -0.27969065  1.22721661 -0.68477479
  -0.29931851 -0.38135202  0.32178351 -1.33760303 -0.47203723 -0.5218311
  -0.09927877 -0.93556584 -0.57967737]
 [ 1.09253556 -0.1491633  -1.04578721 -0.27969065 -0.81485207 -0.68477479
  -0.29931851  2.62224913  0.32178351 -1.81074148 -0.47203723 -0.5218311
  -0.09927877  1.06887186 -0.57967737]
 [ 1.09253556 -0.1491633  -1.04578721 -0.27969065  1.22721661 -0.68477479
  -0.29931851 -0.38135202  1.3259909  -0.86446457 -0.47203723 -0.5218311
  -0.09927877  1.06887186 -0.57967737]
 [-0.91530201 -0.1491633   0.95621747 -0.27969065 -0.81485207 -0.68477479
  -0.29931851  2.62224913 -0.68242389  0.55495079 -0.47203723 -0.5218311
  -0.09927877  1.06887186  1.72509754]
 [-0.91530201 -0.1491633   0.95621747 -0.27969065 -0.81485207  1.4603

**Logistic Regression(Classification)

In [23]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[73 10]
 [22  8]]


0.7168141592920354

**Decision Tree Classifier

In [25]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[83  0]
 [ 2 28]]


0.9823008849557522

**Random Forest Classifier

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[83  0]
 [ 3 27]]


0.9734513274336283

**K Nearest Neighbours Classification

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[80  3]
 [ 6 24]]


0.9203539823008849

**SVM (Linear)

In [31]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[74  9]
 [23  7]]


0.7168141592920354

**Kernel SVM

In [34]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[79  4]
 [15 15]]


0.831858407079646

**Naive Bayes

In [36]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[60 23]
 [16 14]]


0.6548672566371682

**ANN

In [50]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 7, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 7, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [53]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 1000)

Train on 827 samples
Epoch 1/1000
827/827 [==============================] - 0s 421us/sample - loss: 0.1336 - accuracy: 0.9541
Epoch 2/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.1315 - accuracy: 0.9553
Epoch 3/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1315 - accuracy: 0.9577
Epoch 4/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1313 - accuracy: 0.9565
Epoch 5/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1311 - accuracy: 0.9577
Epoch 6/1000
827/827 [==============================] - 0s 47us/sample - loss: 0.1313 - accuracy: 0.9528
Epoch 7/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1318 - accuracy: 0.9565
Epoch 8/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.1309 - accuracy: 0.9553
Epoch 9/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.1308 - accuracy: 0.9541
Epoch 10/1000
827/827 [==========

827/827 [==============================] - 0s 48us/sample - loss: 0.1285 - accuracy: 0.9565
Epoch 79/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1271 - accuracy: 0.9577
Epoch 80/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1283 - accuracy: 0.9553
Epoch 81/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.1268 - accuracy: 0.9577
Epoch 82/1000
827/827 [==============================] - 0s 58us/sample - loss: 0.1275 - accuracy: 0.9577
Epoch 83/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.1263 - accuracy: 0.9553
Epoch 84/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.1273 - accuracy: 0.9565
Epoch 85/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1268 - accuracy: 0.9553
Epoch 86/1000
827/827 [==============================] - 0s 34us/sample - loss: 0.1266 - accuracy: 0.9577
Epoch 87/1000
827/827 [==============================] - 0s 

827/827 [==============================] - 0s 44us/sample - loss: 0.1191 - accuracy: 0.9613
Epoch 155/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1195 - accuracy: 0.9661
Epoch 156/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1204 - accuracy: 0.9553
Epoch 157/1000
827/827 [==============================] - 0s 43us/sample - loss: 0.1184 - accuracy: 0.9637
Epoch 158/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1190 - accuracy: 0.9637
Epoch 159/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1189 - accuracy: 0.9601
Epoch 160/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.1201 - accuracy: 0.9649
Epoch 161/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1199 - accuracy: 0.9577
Epoch 162/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1206 - accuracy: 0.9613
Epoch 163/1000
827/827 [============================

827/827 [==============================] - 0s 39us/sample - loss: 0.1100 - accuracy: 0.9674
Epoch 231/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1113 - accuracy: 0.9625
Epoch 232/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1090 - accuracy: 0.9625
Epoch 233/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1095 - accuracy: 0.9625
Epoch 234/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1089 - accuracy: 0.9649
Epoch 235/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1093 - accuracy: 0.9674
Epoch 236/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1085 - accuracy: 0.9637
Epoch 237/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1103 - accuracy: 0.9565
Epoch 238/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1094 - accuracy: 0.9661
Epoch 239/1000
827/827 [============================

827/827 [==============================] - 0s 44us/sample - loss: 0.1030 - accuracy: 0.9674
Epoch 307/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1031 - accuracy: 0.9637
Epoch 308/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1042 - accuracy: 0.9649
Epoch 309/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1055 - accuracy: 0.9661
Epoch 310/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1048 - accuracy: 0.9625
Epoch 311/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1013 - accuracy: 0.9686
Epoch 312/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1026 - accuracy: 0.9661
Epoch 313/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.1038 - accuracy: 0.9674
Epoch 314/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.1032 - accuracy: 0.9686
Epoch 315/1000
827/827 [============================

827/827 [==============================] - 0s 53us/sample - loss: 0.0976 - accuracy: 0.9698
Epoch 383/1000
827/827 [==============================] - 0s 58us/sample - loss: 0.0977 - accuracy: 0.9674
Epoch 384/1000
827/827 [==============================] - 0s 53us/sample - loss: 0.0969 - accuracy: 0.9686
Epoch 385/1000
827/827 [==============================] - 0s 53us/sample - loss: 0.0985 - accuracy: 0.9698
Epoch 386/1000
827/827 [==============================] - 0s 63us/sample - loss: 0.0981 - accuracy: 0.9686
Epoch 387/1000
827/827 [==============================] - 0s 58us/sample - loss: 0.0967 - accuracy: 0.9661
Epoch 388/1000
827/827 [==============================] - 0s 53us/sample - loss: 0.0996 - accuracy: 0.9661
Epoch 389/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0984 - accuracy: 0.9686
Epoch 390/1000
827/827 [==============================] - 0s 53us/sample - loss: 0.0986 - accuracy: 0.9674
Epoch 391/1000
827/827 [============================

827/827 [==============================] - 0s 44us/sample - loss: 0.0925 - accuracy: 0.9710
Epoch 459/1000
827/827 [==============================] - 0s 43us/sample - loss: 0.0937 - accuracy: 0.9674
Epoch 460/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0943 - accuracy: 0.9686
Epoch 461/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0952 - accuracy: 0.9686
Epoch 462/1000
827/827 [==============================] - 0s 43us/sample - loss: 0.0958 - accuracy: 0.9674
Epoch 463/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0958 - accuracy: 0.9674
Epoch 464/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0912 - accuracy: 0.9722
Epoch 465/1000
827/827 [==============================] - 0s 45us/sample - loss: 0.0924 - accuracy: 0.9722
Epoch 466/1000
827/827 [==============================] - 0s 45us/sample - loss: 0.0923 - accuracy: 0.9661
Epoch 467/1000
827/827 [============================

827/827 [==============================] - 0s 44us/sample - loss: 0.0896 - accuracy: 0.9698
Epoch 535/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0902 - accuracy: 0.9661
Epoch 536/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0895 - accuracy: 0.9661
Epoch 537/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0897 - accuracy: 0.9710
Epoch 538/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0895 - accuracy: 0.9686
Epoch 539/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0915 - accuracy: 0.9686
Epoch 540/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0891 - accuracy: 0.9674
Epoch 541/1000
827/827 [==============================] - 0s 53us/sample - loss: 0.0887 - accuracy: 0.9710
Epoch 542/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0904 - accuracy: 0.9698
Epoch 543/1000
827/827 [============================

827/827 [==============================] - 0s 53us/sample - loss: 0.0881 - accuracy: 0.9674
Epoch 611/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0886 - accuracy: 0.9686
Epoch 612/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0865 - accuracy: 0.9686
Epoch 613/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0863 - accuracy: 0.9710
Epoch 614/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0863 - accuracy: 0.9674
Epoch 615/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0880 - accuracy: 0.9649
Epoch 616/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0884 - accuracy: 0.9661
Epoch 617/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0876 - accuracy: 0.9710
Epoch 618/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0860 - accuracy: 0.9710
Epoch 619/1000
827/827 [============================

827/827 [==============================] - 0s 44us/sample - loss: 0.0836 - accuracy: 0.9698
Epoch 687/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0834 - accuracy: 0.9698
Epoch 688/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0821 - accuracy: 0.9722
Epoch 689/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0823 - accuracy: 0.9710
Epoch 690/1000
827/827 [==============================] - 0s 42us/sample - loss: 0.0816 - accuracy: 0.9698
Epoch 691/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0824 - accuracy: 0.9722
Epoch 692/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0832 - accuracy: 0.9674
Epoch 693/1000
827/827 [==============================] - 0s 41us/sample - loss: 0.0837 - accuracy: 0.9734
Epoch 694/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0837 - accuracy: 0.9674
Epoch 695/1000
827/827 [============================

827/827 [==============================] - 0s 48us/sample - loss: 0.0789 - accuracy: 0.9710
Epoch 763/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0807 - accuracy: 0.9722
Epoch 764/1000
827/827 [==============================] - 0s 42us/sample - loss: 0.0814 - accuracy: 0.9758
Epoch 765/1000
827/827 [==============================] - 0s 43us/sample - loss: 0.0796 - accuracy: 0.9734
Epoch 766/1000
827/827 [==============================] - 0s 43us/sample - loss: 0.0800 - accuracy: 0.9674
Epoch 767/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0777 - accuracy: 0.9734
Epoch 768/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0789 - accuracy: 0.9722
Epoch 769/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0798 - accuracy: 0.9722
Epoch 770/1000
827/827 [==============================] - 0s 43us/sample - loss: 0.0792 - accuracy: 0.9734
Epoch 771/1000
827/827 [============================

827/827 [==============================] - 0s 44us/sample - loss: 0.0757 - accuracy: 0.9746
Epoch 839/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0761 - accuracy: 0.9746
Epoch 840/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0760 - accuracy: 0.9758
Epoch 841/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0765 - accuracy: 0.9722
Epoch 842/1000
827/827 [==============================] - 0s 45us/sample - loss: 0.0777 - accuracy: 0.9734
Epoch 843/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0785 - accuracy: 0.9722
Epoch 844/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0764 - accuracy: 0.9734
Epoch 845/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0738 - accuracy: 0.9770
Epoch 846/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0761 - accuracy: 0.9710
Epoch 847/1000
827/827 [============================

827/827 [==============================] - 0s 43us/sample - loss: 0.0775 - accuracy: 0.9710
Epoch 915/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0719 - accuracy: 0.9758
Epoch 916/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0723 - accuracy: 0.9746
Epoch 917/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0722 - accuracy: 0.9746
Epoch 918/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0728 - accuracy: 0.9794
Epoch 919/1000
827/827 [==============================] - 0s 43us/sample - loss: 0.0737 - accuracy: 0.9758
Epoch 920/1000
827/827 [==============================] - 0s 39us/sample - loss: 0.0750 - accuracy: 0.9758
Epoch 921/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0741 - accuracy: 0.9758
Epoch 922/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0736 - accuracy: 0.9782
Epoch 923/1000
827/827 [============================

827/827 [==============================] - 0s 48us/sample - loss: 0.0697 - accuracy: 0.9758
Epoch 991/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0692 - accuracy: 0.9807
Epoch 992/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0748 - accuracy: 0.9734
Epoch 993/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0699 - accuracy: 0.9782
Epoch 994/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0691 - accuracy: 0.9794
Epoch 995/1000
827/827 [==============================] - 0s 49us/sample - loss: 0.0716 - accuracy: 0.9758
Epoch 996/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0702 - accuracy: 0.9794
Epoch 997/1000
827/827 [==============================] - 0s 48us/sample - loss: 0.0698 - accuracy: 0.9794
Epoch 998/1000
827/827 [==============================] - 0s 44us/sample - loss: 0.0698 - accuracy: 0.9794
Epoch 999/1000
827/827 [============================